### ISSUE TITLE
Mira on Deta

### ISSUE THREAD

**Issue by abdelhai** [thesephist/mira#3]
Hey Linus, I wanted to run my own Mira, so I ported it to Deta. Here's my repo: https://github.com/abdelhai/mira
It uses Base as a DB, so #1 should be easy to implement since we do have query filters: https://docs.deta.sh/docs/base/sdk#fetch

Cheers!

**Comment by thesephist** [comment]
Yo, this is super cool! Thanks for doing this. I think Mira is one of the projects people most want to deploy on their own so this is neat.

I added a note in the Readme in https://github.com/thesephist/mira/commit/0e34d6ab4d312db0632590a111cf21c87324bb93 about your fork, if people want to deploy on Deta 🚀

**Comment by abdelhai** [comment]
Awesome! Thanks for the link :)
